enabled: true
titleOnly: false
commitsOnly: true
titleAndCommits: false
anyCommit: true
allowMergeCommits: false
allowRevertCommits: true

scopes:
  - prlg
  - ch1
  - ch2
  - ch3
  - ch4
  - ch5
  - ch6
  - ch7
  - ch8
  - check
  - item
  - layout
  - logic
  - map
  - script

types:
  - chore
  - feat
  - fix
  - refactor
  - revert
